# Generated by Django 2.2.3 on 2019-10-04 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptname', models.CharField(max_length=50)),
                ('d_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250)),
                ('file', models.FileField(blank=True, null=True, upload_to='documemts/')),
            ],
        ),
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=250)),
                ('venue', models.CharField(max_length=250)),
                ('fromdate', models.DateField()),
                ('todate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectname', models.CharField(max_length=50)),
                ('coursename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursenames', to='administrator.course')),
                ('deptname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deptnames', to='administrator.Dept')),
            ],
        ),
        migrations.CreateModel(
            name='Studentdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('startbatch', models.IntegerField()),
                ('endbatch', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='studentimages/')),
                ('coursename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coursen', to='administrator.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='administrator.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjec', to='administrator.subject')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernam', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='deptname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deptn', to='administrator.Dept'),
        ),
    ]
