# Generated by Django 2.2.3 on 2019-11-07 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_name', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.IntegerField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('pay_status', models.BooleanField(default=False)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cou', to='administrator.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.Studentdetails')),
            ],
        ),
    ]
