# Generated by Django 2.2.3 on 2019-11-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_auto_20191107_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fee',
        ),
    ]
